name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: clickhouse/clickhouse-server
        ports:
          - 8123:8123
        env:
          CLICKHOUSE_DB: default
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: 123
        options: >-
          --health-cmd="curl -f http://localhost:8123/ping || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --verbose

      - name: Run unit tests
        run: cargo test --lib --verbose

      - name: Run quick tests
        run: cargo test --test integration_test test_config --verbose

      - name: Wait for ClickHouse
        run: |
          timeout 60s bash -c 'until curl -f http://localhost:8123/ping; do sleep 2; done'

      - name: Run integration tests
        run: cargo test --test integration_test test_integration -- --ignored --nocapture
        env:
          CLICKHOUSE_URL: http://localhost:8123

